# Generated by Django 5.1 on 2024-09-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_subscribers_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribers',
            unique_together={('email',)},
        ),
    ]
