# Generated by Django 5.1 on 2024-09-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_document', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdocument',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
