services:
  # WEB service
  web:
    container_name: ${PROJECT_PREFIX}_backend
    env_file: "./containers/prod/.env_prod"
    # restart: always
    build:
      context: ../
      dockerfile: ./docker/containers/prod/web.Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    volumes:
      - ../static:/app/static
      - ../media:/app/media
    ports:
      - ${HTTP_PORT}:8010
      - ${DEBUG_PORT}:3000