services:
  # WEB service
  web:
    container_name: ${PROJECT_PREFIX}_backend
    env_file: "./containers/dev/.env_dev"
    build:
      context: ../
      dockerfile: ./docker/containers/dev/web.Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    volumes:
      - ..:/app  
    ports:
      - ${HTTP_PORT}:8000
      - ${DEBUG_PORT}:3000
    depends_on:
      - pgsql

  # PostgreSQL
  pgsql:
    container_name: ${PROJECT_PREFIX}_pgsql
    env_file: "./containers/dev/.env_dev"
    build:
      context: .
      dockerfile: ./containers/dev/pgsql.Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    hostname: ${DB_HOST}
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data