services:
  # WEB service
  web:
    container_name: ${PROJECT_PREFIX}_backend
    env_file: "./containers/prod/.env_prod"
    build:
      context: ../
      dockerfile: ./docker/containers/prod/web.Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    volumes:
      - ..:/app    
    expose:
      - ${HTTP_PORT}