# Generated by Django 5.1 on 2024-09-06 21:51

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtailmetadata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPageMixin',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_keyword', models.CharField(blank=True, default='', help_text='Ключевые слова для поисковых систем', max_length=255, verbose_name='Ключевые слова')),
                ('seo_site', models.CharField(blank=True, max_length=255, verbose_name='SEO сайт')),
                ('seo_title_footer', models.CharField(blank=True, max_length=200, verbose_name='Заголовок нижнего SEO блока')),
                ('seo_description_footer', models.TextField(blank=True, verbose_name='Заголовок нижнего SEO блока')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ElementsVacanciesSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название элемента вакансии')),
            ],
            options={
                'verbose_name': 'Элемент для вакансии',
                'verbose_name_plural': 'Элементы для вакансии',
            },
        ),
        migrations.CreateModel(
            name='RubricArticlesPage',
            fields=[
                ('seopagemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.seopagemixin')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание рубрики статей')),
            ],
            options={
                'verbose_name': 'Рубрика для статей',
                'verbose_name_plural': 'Рубрики для статей',
                'abstract': False,
            },
            bases=('home.seopagemixin',),
        ),
        migrations.CreateModel(
            name='RubricVacanciesPage',
            fields=[
                ('seopagemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.seopagemixin')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание рубрики вакансий')),
            ],
            options={
                'verbose_name': 'Рубрика для вакансий',
                'verbose_name_plural': 'Рубрики для вакансий',
                'abstract': False,
            },
            bases=('home.seopagemixin',),
        ),
        migrations.CreateModel(
            name='ArticlesPage',
            fields=[
                ('seopagemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.seopagemixin')),
                ('description', wagtail.fields.RichTextField(verbose_name='Описание материала')),
                ('caption_image', models.CharField(max_length=150, null=True, verbose_name='Подпись для изображения')),
                ('image', models.ForeignKey(blank=True, help_text='Выберите подходящее изображение материала из галереи и добавьте сюда', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение для материала')),
            ],
            options={
                'verbose_name': 'Статья для сайта',
                'verbose_name_plural': 'Статьи для сайта',
                'abstract': False,
            },
            bases=('home.seopagemixin',),
        ),
        migrations.CreateModel(
            name='VacanciesPage',
            fields=[
                ('seopagemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.seopagemixin')),
                ('description', wagtail.fields.RichTextField(verbose_name='Описание материала')),
                ('caption_image', models.CharField(max_length=150, null=True, verbose_name='Подпись для изображения')),
                ('url', models.URLField(verbose_name='Партнерская ссылка на вакансию')),
                ('image', models.ForeignKey(blank=True, help_text='Выберите подходящее изображение материала из галереи и добавьте сюда', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение для материала')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'abstract': False,
            },
            bases=('home.seopagemixin',),
        ),
        migrations.CreateModel(
            name='ElementsVacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('content', models.CharField(max_length=150, verbose_name='Описание элемента вакансии')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.elementsvacanciessnippet', verbose_name='Элемент вакансии')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_vacancy', to='home.vacanciespage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
