# Generated by Django 5.1 on 2024-09-07 14:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_elementsvacanciessnippet_alter_homepage_options_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacanciespage',
            name='url',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('vacancies', 3), ('vacancies2', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок блока', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Вакансия', 'page_type': ['home.VacanciesPage']}), 2: ('wagtail.blocks.StructBlock', [[('vacancies', 1)]], {'label': 'Добавить вакансию'}), 3: ('wagtail.blocks.StreamBlock', [[('title', 0), ('vacancies', 2)]], {'label': 'Блок лучших вакансий'})}, verbose_name='Блоки для главной страницы'),
        ),
        migrations.AddField(
            model_name='vacanciespage',
            name='pp_name_button',
            field=models.CharField(max_length=100, null=True, verbose_name='Название для кнопки вакансии'),
        ),
        migrations.AddField(
            model_name='vacanciespage',
            name='pp_url_button',
            field=models.URLField(null=True, verbose_name='Ссылка для кнопки вакансии'),
        ),
        migrations.AlterField(
            model_name='articlespage',
            name='image',
            field=models.ForeignKey(help_text='Выберите подходящее изображение материала из галереи и добавьте сюда', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение для материала'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='image',
            field=models.ForeignKey(help_text='Выберите подходящее изображение материала из галереи и добавьте сюда', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение для материала'),
        ),
    ]
