# Generated by Django 5.1 on 2024-09-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_vacanciespage_url_homepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlespage',
            name='short_description',
            field=models.CharField(max_length=200, null=True, verbose_name='Краткое описание материала'),
        ),
        migrations.AddField(
            model_name='vacanciespage',
            name='short_description',
            field=models.CharField(max_length=200, null=True, verbose_name='Краткое описание материала'),
        ),
    ]
