# Generated by Django 5.1 on 2024-09-08 12:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_articlespage_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('vacancies', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок блока', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Вакансия', 'page_type': ['home.VacanciesPage']}), 2: ('wagtail.blocks.StructBlock', [[('vacancies', 1)]], {'label': 'Добавить вакансию'}), 3: ('wagtail.blocks.StreamBlock', [[('title', 0), ('vacancies', 2)]], {'label': 'Блок лучших вакансий'})}, verbose_name='Блоки для главной страницы'),
        ),
    ]
