# Generated by Django 5.1 on 2024-09-08 21:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_body'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderAndFooterSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_logo', models.CharField(max_length=100, verbose_name='Подпись для логотипа')),
                ('header', wagtail.fields.StreamField([('header_block', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название сайта', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Название пункта меню', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница сайта'}), 3: ('wagtail.blocks.StructBlock', [[('name', 1), ('link', 2)]], {'label': 'Выбрать меню'}), 4: ('wagtail.blocks.StreamBlock', [[('block', 3)]], {'label': 'Меню сайта', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title_site', 0), ('menu', 4)]], {})}, verbose_name='Блок шапки сайта')),
                ('footer', wagtail.fields.StreamField([('footer_block', 8)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Копирайт для сайта', 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка на карту сайта', 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Политика конфидициальности', 'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Пользовательское соглашение', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Название пункта меню', 'max_length': 100, 'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница сайта'}), 6: ('wagtail.blocks.StructBlock', [[('name', 4), ('link', 5)]], {'label': 'Выбрать меню'}), 7: ('wagtail.blocks.StreamBlock', [[('block', 6)]], {'label': 'Меню сайта', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('copyright', 0), ('sitemap', 1), ('privacy_policy', 2), ('user_agreement', 3), ('menu', 7)]], {})}, verbose_name='Блок подвала сайта')),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип сайта')),
            ],
            options={
                'verbose_name': 'Блок шапки и подвала',
                'verbose_name_plural': 'Блоки шапки и подвала',
            },
        ),
    ]
