# Generated by Django 5.1 on 2024-09-10 21:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_headerandfootersnippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerandfootersnippet',
            name='footer',
            field=wagtail.fields.StreamField([('footer_block', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Копирайт для сайта', 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка на карту сайта', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок блока', 'max_length': 100, 'required': True}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Добавить политику или соглашение', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('name_block', 2), ('document_block', 3)]], {'label': 'Добавить блок с юридическими документами'}), 5: ('wagtail.blocks.StreamBlock', [[('privacy_policy_block', 4)]], {'label': 'Блок юридических документов'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Название пункта меню', 'max_length': 100, 'required': True}), 7: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница сайта'}), 8: ('wagtail.blocks.StructBlock', [[('name', 6), ('link', 7)]], {'label': 'Выбрать меню'}), 9: ('wagtail.blocks.StreamBlock', [[('block', 8)]], {'label': 'Меню сайта', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('copyright', 0), ('sitemap', 1), ('policy_block', 5), ('menu', 9)]], {})}, verbose_name='Блок подвала сайта'),
        ),
    ]
