# Generated by Django 5.1 on 2024-09-11 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_headerandfootersnippet_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='name_button',
            field=models.CharField(max_length=100, null=True, verbose_name='Название для кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='url_button',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.rubricvacanciespage', verbose_name='Страница для ссылки'),
        ),
    ]
