# Generated by Django 5.1 on 2024-09-14 09:45

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_headerandfootersnippet_footer'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBannerSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', wagtail.fields.RichTextField(verbose_name='Заголовок')),
                ('form', wagtail.fields.StreamField([('form_block', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст для инпута для имени', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Текст для инпута E-mail', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст для кнопки формы', 'max_length': 100, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('name_input', 0), ('email_input', 1), ('button', 2)]], {})}, verbose_name='Блок формы подписки')),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение для главного экрана')),
            ],
            options={
                'verbose_name': 'Блок первого экрана сайта',
                'verbose_name_plural': 'Блоки первого экрана сайта',
            },
        ),
    ]
