# Generated by Django 5.1 on 2024-09-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_mainbannersnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlespage',
            name='title_description_block',
            field=models.CharField(max_length=150, null=True, verbose_name='Название блока для описания'),
        ),
        migrations.AddField(
            model_name='vacanciespage',
            name='title_description_block',
            field=models.CharField(max_length=150, null=True, verbose_name='Название блока для описания'),
        ),
    ]
