# Generated by Django 5.1 on 2024-09-14 15:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_articlespage_title_description_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='name_button',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='url_button',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('vacancies', 6), ('articles', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок блока', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Вакансия', 'page_type': ['home.VacanciesPage']}), 2: ('wagtail.blocks.StructBlock', [[('vacancies', 1)]], {'label': 'Добавить вакансию'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Название для кнопки', 'max_length': 100, 'required': True}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Выбрать рубрику'}), 5: ('wagtail.blocks.StructBlock', [[('name', 3), ('url', 4)]], {'label': 'Добавить кнопку на рубрику вакансий'}), 6: ('wagtail.blocks.StreamBlock', [[('title', 0), ('vacancies', 2), ('button', 5)]], {'label': 'Блок вакансий на главной'}), 7: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Статья', 'page_type': ['home.ArticlesPage']}), 8: ('wagtail.blocks.StructBlock', [[('articles', 7)]], {'label': 'Добавить статью'}), 9: ('wagtail.blocks.StructBlock', [[('name', 3), ('url', 4)]], {'label': 'Добавить кнопку на рубрику статей'}), 10: ('wagtail.blocks.StreamBlock', [[('title', 0), ('articles', 8), ('button', 9)]], {'label': 'Блок статей на главной'})}, verbose_name='Блоки для главной страницы'),
        ),
    ]
