# Generated by Django 5.1 on 2024-09-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_homepage_name_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespage',
            name='short_description',
            field=models.CharField(max_length=300, null=True, verbose_name='Краткое описание материала'),
        ),
        migrations.AlterField(
            model_name='rubricarticlespage',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание рубрики статей'),
        ),
        migrations.AlterField(
            model_name='rubricvacanciespage',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание рубрики вакансий'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='short_description',
            field=models.CharField(max_length=300, null=True, verbose_name='Краткое описание материала'),
        ),
    ]
