# Generated by Django 5.1 on 2024-09-17 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_articlespage_short_description_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespage',
            name='search_image',
            field=models.ForeignKey(help_text='Добавьте изображение страницы для поисковых систем', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='SEO Изображение страницы'),
        ),
        migrations.AlterField(
            model_name='articlespage',
            name='seo_description_footer',
            field=models.TextField(verbose_name='Заголовок нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='articlespage',
            name='seo_title_footer',
            field=models.CharField(max_length=200, verbose_name='Заголовок нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='search_image',
            field=models.ForeignKey(help_text='Добавьте изображение страницы для поисковых систем', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='SEO Изображение страницы'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_description_footer',
            field=models.TextField(verbose_name='Заголовок нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_title_footer',
            field=models.CharField(max_length=200, verbose_name='Заголовок нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='rubricarticlespage',
            name='search_image',
            field=models.ForeignKey(help_text='Добавьте изображение страницы для поисковых систем', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='SEO Изображение страницы'),
        ),
        migrations.AlterField(
            model_name='rubricarticlespage',
            name='seo_description_footer',
            field=models.TextField(verbose_name='Заголовок нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='rubricarticlespage',
            name='seo_title_footer',
            field=models.CharField(max_length=200, verbose_name='Заголовок нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='rubricvacanciespage',
            name='search_image',
            field=models.ForeignKey(help_text='Добавьте изображение страницы для поисковых систем', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='SEO Изображение страницы'),
        ),
        migrations.AlterField(
            model_name='rubricvacanciespage',
            name='seo_description_footer',
            field=models.TextField(verbose_name='Заголовок нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='rubricvacanciespage',
            name='seo_title_footer',
            field=models.CharField(max_length=200, verbose_name='Заголовок нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='search_image',
            field=models.ForeignKey(help_text='Добавьте изображение страницы для поисковых систем', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='SEO Изображение страницы'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='seo_description_footer',
            field=models.TextField(verbose_name='Заголовок нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='seo_title_footer',
            field=models.CharField(max_length=200, verbose_name='Заголовок нижнего SEO блока'),
        ),
    ]
