# Generated by Django 5.1 on 2024-09-27 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_articlespage_search_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainbannersnippet',
            name='form',
        ),
    ]
