# Generated by Django 5.1 on 2024-10-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_mainbannersnippet_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlespage',
            name='is_send_email',
            field=models.BooleanField(default=False, verbose_name='Флаг отправки email'),
        ),
        migrations.AddField(
            model_name='vacanciespage',
            name='is_send_email',
            field=models.BooleanField(default=False, verbose_name='Флаг отправки email'),
        ),
    ]
