# Generated by Django 5.1 on 2024-10-03 21:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_articlespage_is_send_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerandfootersnippet',
            name='footer',
            field=wagtail.fields.StreamField([('footer_block', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Копирайт для сайта', 'max_length': 250, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок блока', 'max_length': 100, 'required': True}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Добавить политику или соглашение', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('name_block', 1), ('document_block', 2)]], {'label': 'Добавить блок с юридическими документами'}), 4: ('wagtail.blocks.StreamBlock', [[('privacy_policy_block', 3)]], {'label': 'Блок юридических документов'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Название пункта меню', 'max_length': 100, 'required': True}), 6: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница сайта'}), 7: ('wagtail.blocks.StructBlock', [[('name', 5), ('link', 6)]], {'label': 'Выбрать меню'}), 8: ('wagtail.blocks.StreamBlock', [[('block', 7)]], {'label': 'Меню сайта', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('copyright', 0), ('policy_block', 4), ('menu', 8)]], {})}, verbose_name='Блок подвала сайта'),
        ),
    ]
