# Generated by Django 5.1 on 2024-10-05 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_document', '0003_customdocument_source'),
        ('home', '0018_alter_headerandfootersnippet_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerandfootersnippet',
            name='agreement_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_document.customdocument', verbose_name='Документ согласия на обработку данных'),
        ),
    ]
