# Generated by Django 5.1 on 2024-10-05 15:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_document', '0003_customdocument_source'),
        ('home', '0019_headerandfootersnippet_agreement_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerandfootersnippet',
            name='cookie_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_document.customdocument', verbose_name='Документ обработки cookie'),
        ),
        migrations.AddField(
            model_name='headerandfootersnippet',
            name='policy_personal_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_document.customdocument', verbose_name='Документ обработки персональных данных'),
        ),
        migrations.AddField(
            model_name='headerandfootersnippet',
            name='privacy_policy_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_document.customdocument', verbose_name='Документ политики конфидициальности'),
        ),
        migrations.AlterField(
            model_name='headerandfootersnippet',
            name='agreement_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_document.customdocument', verbose_name='Документ согласия на обработку данных'),
        ),
        migrations.AlterField(
            model_name='headerandfootersnippet',
            name='footer',
            field=wagtail.fields.StreamField([('footer_block', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Копирайт для сайта', 'max_length': 250, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Название пункта меню', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница сайта'}), 3: ('wagtail.blocks.StructBlock', [[('name', 1), ('link', 2)]], {'label': 'Выбрать меню'}), 4: ('wagtail.blocks.StreamBlock', [[('block', 3)]], {'label': 'Меню сайта', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('copyright', 0), ('menu', 4)]], {})}, verbose_name='Блок подвала сайта'),
        ),
    ]
