# Generated by Django 5.1 on 2024-10-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_headerandfootersnippet_cookie_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespage',
            name='title_description_block',
            field=models.CharField(blank=True, default='Описание', editable=False, max_length=150, null=True, verbose_name='Название блока для описания'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='title_description_block',
            field=models.CharField(blank=True, default='Описание', editable=False, max_length=150, null=True, verbose_name='Название блока для описания'),
        ),
    ]
