# Generated by Django 5.1 on 2024-10-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_articlespage_title_description_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespage',
            name='seo_description_footer',
            field=models.TextField(verbose_name='Описание нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_description_footer',
            field=models.TextField(verbose_name='Описание нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='rubricarticlespage',
            name='seo_description_footer',
            field=models.TextField(verbose_name='Описание нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='rubricvacanciespage',
            name='seo_description_footer',
            field=models.TextField(verbose_name='Описание нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='seo_description_footer',
            field=models.TextField(verbose_name='Описание нижнего SEO блока'),
        ),
    ]
