# Generated by Django 5.1 on 2024-10-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_articlespage_seo_description_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespage',
            name='seo_description_footer',
            field=models.TextField(blank=True, verbose_name='Описание нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='articlespage',
            name='seo_title_footer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_description_footer',
            field=models.TextField(blank=True, verbose_name='Описание нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_title_footer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='rubricarticlespage',
            name='seo_description_footer',
            field=models.TextField(blank=True, verbose_name='Описание нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='rubricarticlespage',
            name='seo_title_footer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='rubricvacanciespage',
            name='seo_description_footer',
            field=models.TextField(blank=True, verbose_name='Описание нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='rubricvacanciespage',
            name='seo_title_footer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='seo_description_footer',
            field=models.TextField(blank=True, verbose_name='Описание нижнего SEO блока'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='seo_title_footer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок нижнего SEO блока'),
        ),
    ]
