# Generated by Django 5.1 on 2024-10-20 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_articlespage_seo_description_footer_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespage',
            name='search_image',
            field=models.ForeignKey(blank=True, help_text='Добавьте изображение страницы для поисковых систем', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='SEO Изображение страницы'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='search_image',
            field=models.ForeignKey(blank=True, help_text='Добавьте изображение страницы для поисковых систем', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='SEO Изображение страницы'),
        ),
        migrations.AlterField(
            model_name='rubricarticlespage',
            name='search_image',
            field=models.ForeignKey(blank=True, help_text='Добавьте изображение страницы для поисковых систем', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='SEO Изображение страницы'),
        ),
        migrations.AlterField(
            model_name='rubricvacanciespage',
            name='search_image',
            field=models.ForeignKey(blank=True, help_text='Добавьте изображение страницы для поисковых систем', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='SEO Изображение страницы'),
        ),
        migrations.AlterField(
            model_name='vacanciespage',
            name='search_image',
            field=models.ForeignKey(blank=True, help_text='Добавьте изображение страницы для поисковых систем', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='SEO Изображение страницы'),
        ),
    ]
