# Generated by Django 5.1 on 2024-09-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_yandex', models.IntegerField(blank=True, null=True, verbose_name='Яндекс.Метрика - Идентификатор счётчика аналитики')),
                ('google_analytics', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Analytics - Идентификатор счётчика аналитики')),
                ('yandex_webmaster', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yandex webmaster - Индентификатор счетчика кабинета вебмастер')),
                ('google_webmaster', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google webmaster - Индентификатор счетчика кабинета вебмастер')),
            ],
            options={
                'verbose_name': 'SEO',
            },
        ),
    ]
